version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # User name has to match the 'user' argument for personalization to work
        USER: node
        GROUP: node
    # Non-root user
    user: node

    volumes:
      - ..:/workspace:cached
      - ./.zshrc:/home/node/.zshrc:cached
      - ./.home-overrides/.p10k.zsh:/home/node/.p10k.zsh:cached
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db